version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aircraft-web:
    build:
      target: development
    image: aircraft-web-development
    container_name: aircraft-web-development
    ports:
      - "3000:3000"
      - "9231:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      REDIS_HOST: aircraft-redis

  aircraft-redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

volumes:
  redis_data:
