{{- include "helm-library.container-secret" (list . "aircraft-web.container-secret") -}}
{{- define "aircraft-web.container-secret" -}}
stringData:
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
