environment: production
name: aircraft-web
image: aircraft-web

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  redisHost: services.lynxmagnus.com

deployment: {}

ingress:
  host: aircraft.lynxmagnus.com

secret:
  secretsPath: /aircraft-web
